name: <workflow name>
on: 
  push:
    branches:
      - main

jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Build & Run
      run: gcc -o sobel sobel.c
