name: Mon_Workflow
on: 
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: SDLIB
      run: sudo apt-get install libsdl2-dev
      
    - name: SDLIBTTF
      run: sudo apt-get install libsdl2-ttf-dev
      
    - name: Make generation
      run: ./CMakeGCC.sh
    
    - name: Build and run
      run: make bin/make/Makefile
      
    - name: Make generation
      run: ./bin/make/Release/Sobel
          
